### ISSUE TITLE
Error Handling in Parsing

### ISSUE THREAD

**Issue by nodh** [a-sit-plus/kmp-crypto#12]
Mark possible errors in parsing in an annotation `@Throws`. Because every other exception is unchecked, and Swift only has checked errors, so anything unexpected causes program termination, see [Errors and exceptions](https://kotlinlang.org/docs/native-objc-interop.html#errors-and-exceptions).

**Comment by JesusMcCloud** [comment]
we can always introduce `decodeXXXorNull` functions too. I'm not such a fan of encapsulating all parsing logic everywhere in result classes, because things can and will go wrong badly. Just imagine a stream being a source and not a bytearray.

So yes. annotations and documentation is really crucial here and we probably need an initial code review to cover what he have, and pay attention to this when reviewing PRs

**Comment by JesusMcCloud** [comment]
we should go for `xxxOrNull` functions as recommended by Mr. Kotlin. @n0900 needs new tasks anyhow ;-)
